namespace: epfl_si
name: quay

version: 0.6.5

readme: README.md

authors:
- EPFL SI ISAS-FSD <isas-fsd@groupes.epfl.ch>

description: Ansible for the Quay API

license:
- GPL-2.0-or-later

tags:
- quay

dependencies:
  epfl_si.actions: ">=2.4.0"

repository: https://github.com/epfl-si/ansible-collection-quay

documentation: https://github.com/epfl-si/ansible-collection-quay

homepage: https://github.com/epfl-si/ansible-collection-quay

# The URL to the collection issue tracker
issues: https://github.com/epfl-si/ansible-collection-quay/issues

build_ignore: []
